### ISSUE TITLE
Multiple submissions possible for non-logged users when setting is deactivated

### ISSUE THREAD

**Issue by larsUE** [alecslupu-pfa/decidim-module-survey_multiple_answers#9]
As a non-logged user, I can submit a survey multiple times even when the "Allow multiple answers" checkbox is deactivated. 

Example: https://mitwirken.stadt-zuerich.ch/processes/schipferhof/f/467/?locale=en

### Cases

Case: Survey, where multiple answers should not be possible and no checkboxes of the module are activated.

As a **non-logged user** I can fill out the form. When I submit the form, I get a small success callout, but I can resubmit the form without a problem. This is the same behavior to when multiple answers are activated.

![image002](https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/assets/60926257/68989bec-0416-4107-9b54-fb568a71d0b1)

As a logged user, I can only submit the survey once. Afterwards, I get the success callout on top and the confirmation message in the survey field. I cannot submit the survey multiple times. This is the decidim standard.

<img width="1347" alt="Bildschirmfoto 2023-11-20 um 11 03 05" src="https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/assets/60926257/7a74d4a2-278e-47f9-a2d0-d4875dc81cd7">

###Expected behavior

I expect the behavior for non-logged users to be the same as for logged users.

Expected behaviour is reproducible on try.decidim.org:
<img width="1687" alt="Bildschirmfoto 2023-11-20 um 11 09 54" src="https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/assets/60926257/9a83cf6a-1140-452f-a6dc-3d4ba2a6b169">

**Comment by alecslupu** [comment]
@larsUE I have tested the bug you have mentioned, and i could not find anything wrong on my end ( having the **Allow multiple answers** checkboxes unchecked ) the survey form will not allow me to submit the form multiple times.

**Comment by larsUE** [comment]
Fixed via https://github.com/alecslupu-pfa/decidim-module-survey_multiple_answers/pull/8. Thanks a lot!
